
erwin:
  name: 冯文议
  age: 20
  sex: 男
  english-name: Erwin Feng
  birthday: 1992/02/26
  like: movie,game,music,tea,travel
  visitedCities: 巴中,揭阳,广州,从化,成都,三亚,上海,杭州,北京
  moreOther: {myWeb:'https://fengwenyi.com',github:'https://github.com/fengwenyi'}

author:
  name: 冯文议-yml
  age: 20
  sex: 男
  english-name: Erwin Feng
  birthday: 1992/02/26
  like:
    - movie
    - game
    - music
    - tea
    - travel
  visitedCities: 巴中,揭阳,广州,从化,成都,三亚,上海,杭州,北京
  moreOther:
    myWeb: https://fengwenyi.com
    github: https://github.com/fengwenyi

db:
  host: localhost
  port: 3306
  db-name: test
  username: root
  password: 123456
  connPoolList:
    - type: type1
      name: name1
    - type: type2
      name: name2
    - type: type3
      name: name3